// eslint-disable-next-line no-undef
const Actions = {
    LOAD_PROMOTION_LIST: 'LOAD_PROMOTION_LIST',
    LOAD_PROMOTION_LIST_RESPONSE: 'LOAD_PROMOTION_LIST_RESPONSE',
    LOAD_PROMOTION_LIST_RESPONSE_MOBILE:'LOAD_PROMOTION_LIST_RESPONSE_MOBILE',
    LOADING_PROMOTION_LIST:"LOADING_PROMOTION_LIST",
    LOAD_PROMOTION_LIST_FAIL:"LOAD_PROMOTION_LIST_FAIL",

    LOAD_PROMOTION_DETAIL: 'LOAD_PROMOTION_DETAIL',
    LOAD_PROMOTION_DETAIL_RESPONSE: 'LOAD_PROMOTION_DETAIL_RESPONSE',

    LOAD_OTHER_PROMOTION: 'LOAD_OTHER_PROMOTION',

    LOAD_PROMOTION_LIST_MOBILE:'LOAD_PROMOTION_LIST_MOBILE',
    LOAD_PROMOTION_LIST_FAIL_MOBILE:'LOAD_PROMOTION_LIST_FAIL_MOBILE',
};
export default Actions;
