const MenuActions = {
    FETCH_KEYWORD_SEARCH: 'FETCH_KEYWORD_SEARCH',
    FETCH_KEYWORD_SEARCH_SUCCESS: 'FETCH_KEYWORD_SEARCH_SUCCESS',
    FETCH_KEYWORD_SEARCH_FAILURE: 'FETCH_KEYWORD_SEARCH_FAILURE',

    FETCH_KEYWORD_SEARCH_SCREEN: 'FETCH_KEYWORD_SEARCH_SCREEN',
    FETCH_KEYWORD_SEARCH_SCREEN_SUCCESS: 'FETCH_KEYWORD_SEARCH_SCREEN_SUCCESS',

    OPEN_SEARCH_INPUT: 'OPEN_SEARCH_INPUT',
    CLOSE_SEARCH_INPUT: 'CLOSE_SEARCH_INPUT'
}

export default MenuActions;