export const MasterActions = {
    GET_GENDER_MASTER: "GET_GENDER_MASTER",
    GET_PROVINCE_MASTER: "GET_PROVINCE_MASTER",
    GET_PROVINCE_MASTER_SUCCESS: "GET_PROVINCE_MASTER_SUCCESS",
    GET_DISTRICT_MASTER: "GET_DISTRICT_MASTER",
    GET_COMMUNE_MASTER: "GET_COMMUNE_MASTER",
};

export default MasterActions;
