const actions = {

    LOAD_UNIT_SHIPMENT: 'LOAD_UNIT_SHIPMENT',
    LOADING_UNIT_SHIPMENT: 'LOADING_UNIT_SHIPMENT',
    LOAD_UNIT_SHIPMENT_SUCCESS: 'LOAD_UNIT_SHIPMENT_SUCCESS',
    LOAD_UNIT_SHIPMENT_FAILURE: 'LOAD_UNIT_SHIPMENT_FAILURE',

    LOAD_SHIP_STATUS: 'LOAD_SHIP_STATUS',
    LOADING_SHIP_STATUS: 'LOADING_SHIP_STATUS',
    LOAD_SHIP_STATUS_SUCCESS: 'LOAD_SHIP_STATUS_SUCCESS',
    LOAD_SHIP_STATUS_FAILURE: 'LOAD_SHIP_STATUS_FAILURE',

    LOAD_PAYMENT_STT: 'LOAD_PAYMENT_STT',
    LOADING_PAYMENT_STT: 'LOADING_PAYMENT_STT',
    LOAD_PAYMENT_STT_SUCCESS: 'LOAD_PAYMENT_STT_SUCCESS',
    LOAD_PAYMENT_STT_FAILURE: 'LOAD_PAYMENT_STT_FAILURE',

    LOAD_ITEM_TYPE: 'LOAD_ITEM_TYPE',
    LOADING_ITEM_TYPE: 'LOADING_ITEM_TYPE',
    LOAD_ITEM_TYPE_SUCCESS: 'LOAD_ITEM_TYPE_SUCCESS',
    LOAD_ITEM_TYPE_FAILURE: 'LOAD_ITEM_TYPE_FAILURE',

    LOAD_GENDER: 'LOAD_GENDER',
    LOADING_GENDER: 'LOADING_GENDER',
    LOAD_GENDER_SUCCESS: 'LOAD_GENDER_SUCCESS',
    LOAD_GENDER_FAILURE: 'LOAD_GENDER_FAILURE',


    LOAD_BRAND_MASTER_FULL : 'LOAD_BRAND_MASTER_FULL',
    LOAD_BRAND_MASTER_FULL_SUCCESS : 'LOAD_BRAND_MASTER_FULL_SUCCESS',
    LOAD_BRAND_MASTER_FULL_FAILURE : 'LOAD_BRAND_MASTER_FULL_FAILURE',

    LOAD_SPO_BRAND:"LOAD_SPO_BRAND",
    LOADING_SPO_BRAND:"LOADING_SPO_BRAND",
    LOAD_SPO_BRAND_SUCCESS:"LOAD_SPO_BRAND_SUCCESS",
    LOAD_SPO_BRAND_FAILURE:"LOAD_SPO_BRAND_FAILURE",

    LOAD_HOTTREND: 'LOAD_HOTTREND',
    LOADING_HOTTREND: 'LOADING_HOTTREND',
    LOAD_HOTTREND_SUCCESS: 'LOAD_HOTTREND_SUCCESS',
    LOAD_HOTTREND_FAILURE: 'LOAD_HOTTREND_FAILURE',

    LOAD_IMPRESS_SHOP: 'LOAD_IMPRESS_SHOP',
    LOADING_IMPRESS_SHOP: 'LOADING_IMPRESS_SHOP',
    LOAD_IMPRESS_SHOP_SUCCESS: 'LOAD_IMPRESS_SHOP_SUCCESS',
    LOAD_IMPRESS_SHOP_FAILURE: 'LOAD_IMPRESS_SHOP_FAILURE',

    LOAD_COLLECTION: 'LOAD_COLLECTION',
    LOADING_COLLECTION: 'LOADING_COLLECTION',
    LOAD_COLLECTION_SUCCESS: 'LOAD_COLLECTION_SUCCESS',
    LOAD_COLLECTION_FAILURE: 'LOAD_COLLECTION_FAILURE',

    LOAD_TOP_BRAND: 'LOAD_TOP_BRAND',
    LOADING_TOP_BRAND: 'LOADING_TOP_BRAND',
    LOAD_TOP_BRAND_SUCCESS: 'LOAD_TOP_BRAND_SUCCESS',
    LOAD_TOP_BRAND_FAILURE: 'LOAD_TOP_BRAND_FAILURE',


    LOAD_SIZE : 'LOAD_SIZE',
    LOADING_SIZE : 'LOADING_SIZE',
    LOAD_SIZE_SUCCESS: 'LOAD_SIZE_SUCCESS',
    LOAD_SIZE_FAILURE: 'LOAD_SIZE_FAILURE',

    LOAD_COLOR : 'LOAD_COLOR',
    LOADING_COLOR : 'LOADING_COLOR',
    LOAD_COLOR_SUCCESS: 'LOAD_COLOR_SUCCESS',
    LOAD_COLOR_FAILURE: 'LOAD_COLOR_FAILURE',

    LOAD_COLOR_FILTER : 'LOAD_COLOR_FILTER',
    LOADING_COLOR_FILTER : 'LOADING_COLOR_FILTER',
    LOAD_COLOR_FILTER_SUCCESS: 'LOAD_COLOR_FILTER_SUCCESS',
    LOAD_COLOR_FILTER_FAILURE: 'LOAD_COLOR_FILTER_FAILURE',

    LOAD_SIZE_FILTER : 'LOAD_SIZE_FILTER',
    LOADING_SIZE_FILTER : 'LOADING_SIZE_FILTER',
    LOAD_SIZE_FILTER_SUCCESS: 'LOAD_SIZE_FILTER_SUCCESS',
    LOAD_SIZE_FILTER_FAILURE: 'LOAD_SIZE_FILTER_FAILURE',
    //
    

    LOAD_BANKING_MASTER : 'LOAD_BANKING_MASTER',
    LOADING_BANKING_MASTER : 'LOADING_BANKING_MASTER',
    LOAD_BANKING_MASTER_SUCCESS: 'LOAD_BANKING_MASTER_SUCCESS',
    LOAD_BANKING_MASTER_FAILURE: 'LOAD_BANKING_MASTER_FAILURE',

    LOAD_BRANCH_MASTER : 'LOAD_BRANCH_MASTER',
    LOADING_BRANCH_MASTER : 'LOADING_BRANCH_MASTER',
    LOAD_BRANCH_MASTER_SUCCESS: 'LOAD_BRANCH_MASTER_SUCCESS',
    LOAD_BRANCH_MASTER_FAILURE: 'LOAD_BRANCH_MASTER_FAILURE',

    LOAD_SLIDE : 'LOAD_SLIDE',
    LOADING_SLIDE : 'LOADING_SLIDE',
    LOAD_SLIDE_SUCCESS: 'LOAD_SLIDE_SUCCESS',
    LOAD_SLIDE_FAILURE: 'LOAD_SLIDE_FAILURE',
    
    LOAD_CATEGORY_MASTER: 'LOAD_CATEGORY_MASTER',
    LOADING_CATEGORY_MASTER: 'LOADING_CATEGORY_MASTER',
    LOAD_CATEGORY_MASTER_SUCCESS: 'LOAD_CATEGORY_MASTER_SUCCESS',
    LOAD_CATEGORY_MASTER_FAILURE: 'LOAD_CATEGORY_MASTER_FAILURE',

    LOAD_CATEGORY_MASTER_BY_GENDER: 'LOAD_CATEGORY_MASTER_BY_GENDER',
    LOAD_CATEGORY_MASTER_BY_GENDER_SUCCESS: 'LOAD_CATEGORY_MASTER_BY_GENDER_SUCCESS',

    LOAD_SETTING_MASTER: 'LOAD_SETTING_MASTER',
    LOADING_SETTING_MASTER: 'LOADING_SETTING_MASTER',
    LOAD_SETTING_MASTER_SUCCESS: 'LOAD_SETTING_MASTER_SUCCESS',
    LOAD_SETTING_MASTER_FAILURE: 'LOAD_SETTING_MASTER_FAILURE',
    
    LOAD_RANK_CONFIG_MASTER: 'LOAD_RANK_CONFIG_MASTER',
    LOADING_RANK_CONFIG_MASTER: 'LOADING_RANK_CONFIG_MASTER',
    LOAD_RANK_CONFIG_MASTER_SUCCESS: 'LOAD_RANK_CONFIG_MASTER_SUCCESS',
    LOAD_RANK_CONFIG_MASTER_FAILURE: 'LOAD_RANK_CONFIG_MASTER_FAILURE',

    LOAD_SIZE_MASTER : 'LOAD_SIZE_MASTER',
    LOAD_SIZE_MASTER_SUCCESS: 'LOAD_SIZE_MASTER_SUCCESS',

    LOAD_CATEGORY_MASTER_ALL : 'LOAD_CATEGORY_MASTER_ALL',
    LOAD_CATEGORY_MASTER_ALL_SUCCESS: 'LOAD_CATEGORY_MASTER_ALL_SUCCESS',

    LOAD_RETURN_REASON_SETTING : 'LOAD_RETURN_REASON_SETTING',
    LOAD_RETURN_REASON_SETTING_SUCCESS: 'LOAD_RETURN_REASON_SETTING_SUCCESS',

    LOAD_SHOPPING_GUIDE: 'LOAD_SHOPPING_GUIDE',
    LOADING_SHOPPING_GUIDE: 'LOADING_SHOPPING_GUIDE',
    LOAD_SHOPPING_GUIDE_SUCCESS: 'LOAD_SHOPPING_GUIDE_SUCCESS',
    LOAD_SHOPPING_GUIDE_FAILURE: 'LOAD_SHOPPING_GUIDE_FAILURE',
};

export default actions;
