const action = {
    LOAD_TRACKING_ORDER: 'LOAD_TRACKING_ORDER',
    LOAD_TRACKING_ORDER_LOADING: 'LOAD_TRACKING_ORDER_LOADING',
    LOAD_TRACKING_ORDER_SUCCESS: 'LOAD_TRACKING_ORDER_SUCCESS',
    LOAD_TRACKING_ORDER_FAIL: 'LOAD_TRACKING_ORDER_FAIL',
}

export default action
