// eslint-disable-next-line no-undef
const NewsActions = {
    LOAD_NEWS_LIST: 'LOAD_NEWS_LIST',
    LOAD_NEWS_RESPONSE: 'LOAD_NEWS_RESPONSE',
    LOAD_NEWS_RESPONSE_MOBILE: 'LOAD_NEWS_RESPONSE_MOBILE',
    LOADING_NEWS_LIST:"LOADING_NEWS_LIST",
    LOAD_NEWS_LIST_FAIL:"LOAD_NEWS_LIST_FAIL",

    LOAD_NEWS_DETAIL: 'LOAD_NEWS_DETAIL',
    LOAD_NEWS_DETAIL_RESPONSE: 'LOAD_NEWS_DETAIL_RESPONSE',

    LOAD_NEWS_SLIDE: 'LOAD_NEWS_SLIDE',
    LOAD_NEWS_SLIDE_RESPONSE: 'LOAD_NEWS_SLIDE_RESPONSE',
    LOAD_NEWS_SLIDE_FAIL: 'LOAD_NEWS_SLIDE_FAIL',

    LOAD_OTHER_NEWS: 'LOAD_OTHER_NEWS',

    LOAD_NEWS_MOBILE: 'LOAD_NEWS_MOBILE',
    LOAD_NEWS_FAIL_MOBILE: 'LOAD_NEWS_FAIL_MOBILE',
};

export default NewsActions;
