const RewardActions = {
    LOAD_REWARD_LIST: "LOAD_REWARD_LIST",
    LOAD_REWARD_LIST_SUCCESS: "LOAD_REWARD_LIST_SUCCESS",
    LOAD_REWARD_LIST_FAILURE: "LOAD_REWARD_LIST_FAILURE",

    USER_REWARD_RECEIVE: "USER_REWARD_RECEIVE",
};
export default RewardActions;
