// eslint-disable-next-line no-undef
const MailBoxActions = {
    FETCH_NOTIFICATION_LIST:         'FETCH_NOTIFICATION_LIST',
    FETCH_NOTIFICATION_LIST_SUCCESS: 'FETCH_NOTIFICATION_LIST_SUCCESS',
    FETCH_NOTIFICATION_LIST_FAILURE: 'FETCH_NOTIFICATION_LIST_FAILURE',
	
    FETCH_MESSAGE_LIST:              'FETCH_MESSAGE_LIST',
    FETCH_MESSAGE_LIST_SUCCESS:      'FETCH_MESSAGE_LIST_SUCCESS',
    FETCH_MESSAGE_LIST_FAILURE:      'FETCH_MESSAGE_LIST_FAILURE',
	
    FETCH_NEWS_LIST:                 'FETCH_NEWS_LIST',
    FETCH_NEWS_LIST_SUCCESS:         'FETCH_NEWS_LIST_SUCCESS',
    FETCH_NEWS_LIST_FAILURE:         'FETCH_NEWS_LIST_FAILURE',

    FETCH_PROMOTION_LIST:            'FETCH_PROMOTION_LIST',
    FETCH_PROMOTION_LIST_SUCCESS:    'FETCH_PROMOTION_LIST_SUCCESS',
    FETCH_PROMOTION_LIST_FAILURE:    'FETCH_PROMOTION_LIST_FAILURE',
};

export default MailBoxActions;
