const actions = {
    LOAD_TOP_VIEWED_PRODUCT: 'LOAD_TOP_VIEWED_PRODUCT',
    LOADING_TOP_VIEWED_PRODUCT: 'LOADING_TOP_VIEWED_PRODUCT',
    LOAD_TOP_VIEWED_PRODUCT_SUCCESS: 'LOAD_TOP_VIEWED_PRODUCT_SUCCESS',
    LOAD_TOP_VIEWED_PRODUCT_FAILURE: 'LOAD_TOP_VIEWED_PRODUCT_FAILURE',

    LOAD_NEWEST_PRODUCT: 'LOAD_NEWEST_PRODUCT',
    LOADING_NEWEST_PRODUCT: 'LOADING_NEWEST_PRODUCT',
    LOAD_NEWEST_PRODUCT_SUCCESS: 'LOAD_NEWEST_PRODUCT_SUCCESS',
    LOAD_NEWEST_PRODUCT_FAILURE: 'LOAD_NEWEST_PRODUCT_FAILURE',

    LOAD_GOLDEN_HOUR_PRODUCT: 'LOAD_GOLDEN_HOUR_PRODUCT',
    LOADING_GOLDEN_HOUR_PRODUCT: 'LOADING_GOLDEN_HOUR_PRODUCT',
    LOAD_GOLDEN_HOUR_PRODUCT_SUCCESS: 'LOAD_GOLDEN_HOUR_PRODUCT_SUCCESS',
    LOAD_GOLDEN_HOUR_PRODUCT_FAILURE: 'LOAD_GOLDEN_HOUR_PRODUCT_FAILURE',

    LOAD_SUPPER_SALE_PRODUCT: 'LOAD_SUPPER_SALE_PRODUCT',
    LOADING_SUPPER_SALE_PRODUCT: 'LOADING_SUPPER_SALE_PRODUCT',
    LOAD_SUPPER_SALE_PRODUCT_SUCCESS: 'LOAD_SUPPER_SALE_PRODUCT_SUCCESS',
    LOAD_SUPPER_SALE_PRODUCT_FAILURE: 'LOAD_SUPPER_SALE_PRODUCT_FAILURE',

    LOAD_TRENDING_PRODUCT: 'LOAD_TRENDING_PRODUCT',
    LOADING_TRENDING_PRODUCT: 'LOADING_TRENDING_PRODUCT',
    LOAD_TRENDING_PRODUCT_SUCCESS: 'LOAD_TRENDING_PRODUCT_SUCCESS',
    LOAD_TRENDING_PRODUCT_FAILURE: 'LOAD_TRENDING_PRODUCT_FAILURE',
    
    LOAD_NEWS: 'LOAD_NEWS',
    LOADING_NEWS: 'LOADING_NEWS',
    LOAD_NEWS_SUCCESS: 'LOAD_NEWS_SUCCESS',
    LOAD_NEWS_FAILURE: 'LOAD_NEWS_FAILURE',

    LOAD_PROMOTION: 'LOAD_PROMOTION',
    LOADING_PROMOTION: 'LOADING_PROMOTION',
    LOAD_PROMOTION_SUCCESS: 'LOAD_PROMOTION_SUCCESS',
    LOAD_PROMOTION_FAILURE: 'LOAD_PROMOTION_FAILURE',

    LOAD_MAY_BE_YOU_CARE_PRODUCT: 'LOAD_MAY_BE_YOU_CARE_PRODUCT',
    LOAD_MAY_BE_YOU_CARE_PRODUCT_SUCCESS: 'LOAD_MAY_BE_YOU_CARE_PRODUCT_SUCCESS',

    LOAD_PRODUCT_FILTER: "LOAD_PRODUCT_FILTER",
    LOAD_PRODUCT_FILTER_SUCCESS: "LOAD_PRODUCT_FILTER_SUCCESS",
    LOAD_PRODUCT_FILTER_FAILURE: "LOAD_PRODUCT_FILTER_FAILURE",

    GET_PRODUCT_IN_HOME: 'GET_PRODUCT_IN_HOME',
    GET_PRODUCT_IN_HOME_SUCCESS: 'GET_PRODUCT_IN_HOME_SUCCESS',
};

export default actions;
