export const actions = {
    LOAD_USER_LOGGED: 'LOAD_USER_LOGGED',
    LOAD_USER_LOGGED_SUCCESS: 'LOAD_USER_LOGGED_SUCCESS',
    LOAD_USER_LOGGED_FAILURE: 'LOAD_USER_LOGGED_FAILURE',

    AUTH_ME: 'AUTH_ME',
    AUTHING_ME: 'AUTHING_ME',
    AUTH_ME_SUCCESS: 'AUTH_ME_SUCCESS',
    AUTH_ME_FAILURE: 'AUTH_ME_FAILURE',

    LOGOUT: 'LOGOUT',

    LOAD_USER_INFO: 'LOAD_USER_INFO',
    LOADING_USER_INFO: 'LOADING_USER_INFO',
    LOAD_USER_INFO_SUCCESS: 'LOAD_USER_INFO_SUCCESS',
    LOAD_USER_INFO_FAILURE: 'LOAD_USER_INFO_FAILURE',

    UPDATE_USER_INFO: 'UPDATE_USER_INFO',
    UPDATING_USER_INFO: 'UPDATING_USER_INFO',
    UPDATE_USER_INFO_SUCCESS: 'UPDATE_USER_INFO_SUCCESS',
    UPDATE_USER_INFO_FAILURE: 'UPDATE_USER_INFO_FAILURE',

    LOAD_USER_ORDER: 'LOAD_USER_ORDER',
    LOADING_USER_ORDER: 'LOADING_USER_ORDER',
    LOAD_USER_ORDER_SUCCESS: 'LOAD_USER_ORDER_SUCCESS',
    LOAD_USER_ORDER_FAILURE: 'LOAD_USER_ORDER_FAILURE',

    LOAD_USER_ADDRESS: 'LOAD_USER_ADDRESS',
    LOADING_USER_ADDRESS: 'LOADING_USER_ADDRESS',
    LOAD_USER_ADDRESS_SUCCESS: 'LOAD_USER_ADDRESS_SUCCESS',
    LOAD_USER_ADDRESS_FAILURE: 'LOAD_USER_ADDRESS_FAILURE',

    ADD_ORDER_ADDRESS: 'ADD_ORDER_ADDRESS',
    ADDING_ORDER_ADDRESS: 'ADDING_ORDER_ADDRESS',
    ADD_ORDER_ADDRESS_SUCCESS: 'ADD_ORDER_ADDRESS_SUCCESS',
    ADD_ORDER_ADDRESS_FAILURE: 'ADD_ORDER_ADDRESS_FAILURE',

    UPDATE_ORDER_ADDRESS: 'UPDATE_ORDER_ADDRESS',
    UPDATING_ORDER_ADDRESS: 'UPDATING_ORDER_ADDRESS',
    UPDATE_ORDER_ADDRESS_SUCCESS: 'UPDATE_ORDER_ADDRESS_SUCCESS',
    UPDATE_ORDER_ADDRESS_FAILURE: 'UPDATE_ORDER_ADDRESS_FAILURE',

    REMOVE_ITEM_ADDRESS_ORDER: 'REMOVE_ITEM_ADDRESS_ORDER',
    REMOVING_ITEM_ADDRESS_ORDER: 'REMOVING_ITEM_ADDRESS_ORDER',
    REMOVE_ITEM_ADDRESS_ORDER_SUCCESS: 'REMOVE_ITEM_ADDRESS_ORDER_SUCCESS',
    REMOVE_ITEM_ADDRESS_ORDER_FAILURE: 'REMOVE_ITEM_ADDRESS_ORDER_FAILURE',

    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    CHANGING_PASSWORD: 'CHANGING_PASSWORD',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',


    UPDATE_AVATAR: 'UPDATE_AVATAR',
    UPDATING_AVATAR: 'UPDATING_AVATAR',
    UPDATE_AVATAR_SUCCESS: 'UPDATE_AVATAR_SUCCESS',
    UPDATE_AVATAR_FAILURE: 'UPDATE_AVATAR_FAILURE',

    UPDATE_DEFAULT_ADDRESS: 'UPDATE_DEFAULT_ADDRESS',
    UPDATING_DEFAULT_ADDRESS: 'UPDATING_DEFAULT_ADDRESS',
    UPDATE_DEFAULT_ADDRESS_SUCCESS: 'UPDATE_DEFAULT_ADDRESS_SUCCESS',
    UPDATE_DEFAULT_ADDRESS_FAILURE: 'UPDATE_DEFAULT_ADDRESS_FAILURE',

    GET_USER_ADDRESS_DETAIL: 'GET_USER_ADDRESS_DETAIL',
    GETTING_USER_ADDRESS_DETAIL: 'GETTING_USER_ADDRESS_DETAIL',
    GET_USER_ADDRESS_DETAIL_SUCCESS: 'GET_USER_ADDRESS_DETAIL_SUCCESS',
    GET_USER_ADDRESS_DETAIL_FAILURE: 'GET_USER_ADDRESS_DETAIL_FAILURE',

    CLEAR_USER_ADDRESS_DETAIL: 'CLEAR_USER_ADDRESS_DETAIL',

    RESET_USER_LOGGED: 'RESET_USER_LOGGED',
    // QR DATA
    GET_ORDER_QR_DATA: 'GET_ORDER_QR_DATA',
    GET_ORDER_QR_DATA_SUCCESS: 'GET_ORDER_QR_DATA_SUCCESS',
    GET_ORDER_QR_DATA_FAILURE: 'GET_ORDER_QR_DATA_FAILURE',
};

export default actions;
