const actions = {
    LOAD_REVIEWS_FOR_ORDER: 'LOAD_REVIEWS_FOR_ORDER',
    LOAD_REVIEWS_FOR_ORDER_SUCCESS: 'LOAD_REVIEWS_FOR_ORDER_SUCCESS',
    LOAD_REVIEWS_FOR_ORDER_FAILURE: 'LOAD_REVIEWS_FOR_ORDER_FAILURE',

    LOAD_REVIEWS_FOR_CHAT: 'LOAD_REVIEWS_FOR_CHAT',
    LOAD_REVIEWS_FOR_CHAT_SUCCESS: 'LOAD_REVIEWS_FOR_CHAT_SUCCESS',
    LOAD_REVIEWS_FOR_CHAT_FAILURE: 'LOAD_REVIEWS_FOR_CHAT_FAILURE',

    LOAD_SETTING_REVIEW: 'LOAD_SETTING_REVIEW',
    LOAD_SETTING_REVIEW_SUCCESS: 'LOAD_SETTING_REVIEW_SUCCESS',
    LOAD_SETTING_REVIEW_FAILURE: 'LOAD_SETTING_REVIEW_FAILURE',

    SAVE_CHAT_REVIEW: 'SAVE_CHAT_REVIEW',
    SAVE_CHAT_REVIEW_SUCCESS: 'SAVE_CHAT_REVIEW_SUCCESS',
    SAVE_CHAT_REVIEW_FAILURE: 'SAVE_CHAT_REVIEW_FAILURE',

    GET_CHAT_DETAIL: 'GET_CHAT_DETAIL',
    GET_CHAT_DETAIL_SUCCESS: 'GET_CHAT_DETAIL_SUCCESS',
    GET_CHAT_DETAIL_FAILURE: 'GET_CHAT_DETAIL_FAILURE',
};

export default actions;