const actions = {
    LOAD_PRODUCT_DETAIL: 'LOAD_PRODUCT_DETAIL',
    LOADING_PRODUCT_DETAIL: 'LOADING_PRODUCT_DETAIL',
    LOAD_PRODUCT_DETAIL_SUCCESS: 'LOAD_PRODUCT_DETAIL_SUCCESS',
    LOAD_PRODUCT_DETAIL_FAILURE: 'LOAD_PRODUCT_DETAIL_FAILURE',

    LOAD_RELATIVE_PRODUCT: 'LOAD_RELATIVE_PRODUCT',
    LOADING_RELATIVE_PRODUCT: 'LOADING_RELATIVE_PRODUCT',
    LOAD_RELATIVE_PRODUCT_SUCCESS: 'LOAD_RELATIVE_PRODUCT_SUCCESS',
    LOAD_RELATIVE_PRODUCT_FAILURE: 'LOAD_RELATIVE_PRODUCT_FAILURE',

    LOAD_RECENTLY_PRODUCT: 'LOAD_RECENTLY_PRODUCT',
    LOADING_RECENTLY_PRODUCT: 'LOADING_RECENTLY_PRODUCT',
    LOAD_RECENTLY_PRODUCT_SUCCESS: 'LOAD_RECENTLY_PRODUCT_SUCCESS',
    LOAD_RECENTLY_PRODUCT_FAILURE: 'LOAD_RECENTLY_PRODUCT_FAILURE',

    LOAD_PRODUCT_SHOP:"LOAD_PRODUCT_SHOP",
    LOADING_PRODUCT_SHOP:"LOADING_PRODUCT_SHOP",
    LOAD_PRODUCT_SHOP_SUCCESS:"LOAD_PRODUCT_SHOP_SUCCESS",
    LOAD_PRODUCT_SHOP_FAILURE:"LOAD_PRODUCT_SHOP_FAILURE",

    CHANGE_TAB_ACTIVE:"CHANGE_TAB_ACTIVE",

    LOAD_PRODUCT_DETAIL_REVIEW: 'LOAD_PRODUCT_DETAIL_REVIEW',
    LOADING_PRODUCT_DETAIL_REVIEW: 'LOADING_PRODUCT_DETAIL_REVIEW',
    LOAD_PRODUCT_DETAIL_REVIEW_SUCCESS: 'LOAD_PRODUCT_DETAIL_REVIEW_SUCCESS',
    LOAD_PRODUCT_DETAIL_REVIEW_FAILURE: 'LOAD_PRODUCT_DETAIL_REVIEW_FAILURE',

    LOAD_STOCK_INFO: 'LOAD_STOCK_INFO',
    LOAD_STOCK_INFO_SUCCESS: 'LOAD_STOCK_INFO_SUCCESS',

    TOGGLE_WISHLIST_SUCCESS: 'TOGGLE_WISHLIST_SUCCESS',
};

export default actions;
