const actions = {
    LOAD_NEWS: 'LOAD_NEWS',
    LOADING_NEWS: 'LOADING_NEWS',
    LOAD_NEWS_SUCCESS: 'LOAD_NEWS_SUCCESS',
    LOAD_NEWS_FAILURE: 'LOAD_NEWS_FAILURE',

    NO_LOADING: 'NOLOAD',
    LOADING_PROMOTION: 'LOADING_PROMOTION',
    LOAD_PROMOTION_SUCCESS: 'LOAD_PROMOTION_SUCCESS',
    LOAD_PROMOTION_FAILURE: 'LOAD_PROMOTION_FAILURE',
};

export default actions;
