const actions = {
    LOAD_USER_NOTIFICATION: 'LOAD_USER_NOTIFICATION',
    LOADING_USER_NOTIFICATION: 'LOADING_USER_NOTIFICATION',
    LOAD_USER_NOTIFICATION_SUCCESS: 'LOAD_USER_NOTIFICATION_SUCCESS',
    LOAD_USER_NOTIFICATION_FAILURE: 'LOAD_USER_NOTIFICATION_FAILURE',

    UPDATE_STATUS_NOTIFICATION: 'UPDATE_STATUS_NOTIFICATION',
    UPDATING_STATUS_NOTIFICATION: 'UPDATING_STATUS_NOTIFICATION',
    UPDATE_STATUS_NOTIFICATION_SUCCESS: 'UPDATE_STATUS_NOTIFICATION_SUCCESS',
    UPDATE_STATUS_NOTIFICATION_FAILURE: 'UPDATE_STATUS_NOTIFICATION_FAILURE',
};

export default actions;
