const actions = {
    LOAD_CART: 'LOAD_CART',
    LOADING_CART: 'LOADING_CART',
    LOAD_CART_SUCCESS: 'LOAD_CART_SUCCESS',
    LOAD_CART_FAILURE: 'LOAD_CART_FAILURE',
    UPDATE_CHECKED_CART: 'UPDATE_CHECKED_CART',

    UPDATE_CART: 'UPDATE_CART',
    UPDATING_CART: 'UPDATING_CART',
    UPDATE_CART_SUCCESS: 'UPDATE_CART_SUCCESS',
    UPDATE_CART_FAILURE: 'UPDATE_CART_FAILURE',

    ADD_CART: 'ADD_CART',
    ADDING_CART: 'ADDING_CART',
    ADD_CART_SUCCESS: 'ADD_CART_SUCCESS',
    ADD_CART_FAILURE: 'ADD_CART_FAILURE',

    ADD_CART_BY_STOCK: 'ADD_CART_BY_STOCK',
    ADDING_CART_BY_STOCK: 'ADDING_CART_BY_STOCK',
    ADD_CART_BY_STOCK_SUCCESS: 'ADD_CART_BY_STOCK_SUCCESS',
    ADD_CART_BY_STOCK_FAILURE: 'ADD_CART_BY_STOCK_FAILURE',

    REMOVE_ITEM_CART: 'REMOVE_ITEM_CART',
    REMOVING_ITEM_CART: 'REMOVING_ITEM_CART',
    REMOVE_ITEM_CART_SUCCESS: 'REMOVE_ITEM_CART_SUCCESS',
    REMOVE_ITEM_CART_FAILURE: 'REMOVE_ITEM_CART_FAILURE',

    UPDATE_PICK_STOCK: 'UPDATE_PICK_STOCK',
    TOGGLE_PICK_STOCK: 'TOGGLE_PICK_STOCK',

    LOAD_CURRENT_ITEM: 'LOAD_CURRENT_ITEM',
    LOADING_CURRENT_ITEM: 'LOADING_CURRENT_ITEM',
    LOAD_CURRENT_ITEM_SUCCESS: 'LOAD_CURRENT_ITEM_SUCCESS',
    LOAD_CURRENT_ITEM_FAILURE: 'LOAD_CURRENT_ITEM_FAILURE',
    DELETE_CART: 'DELETE_CART',

    BUY_NOW: 'BUY_NOW',
    LOADING_BUY_NOW: 'LOADING_BUY_NOW',
    BUY_NOW_SUCCESS: 'BUY_NOW_SUCCESS',
    BUY_NOW_FAILURE: 'BUY_NOW_FAILURE',

    LOAD_PRODUCT_INFO_BY_ID: 'LOAD_PRODUCT_INFO_BY_ID',
    LOADING_PRODUCT_INFO_BY_ID: 'LOADING_PRODUCT_INFO_BY_ID',
    LOAD_PRODUCT_INFO_BY_ID_SUCCESS: 'LOAD_PRODUCT_INFO_BY_ID_SUCCESS',
    LOAD_PRODUCT_INFO_BY_ID_FAILURE: 'LOAD_PRODUCT_INFO_BY_ID_FAILURE',

    LOAD_RELATIVE_PRODUCT: 'LOAD_RELATIVE_PRODUCT',
    LOADING_RELATIVE_PRODUCT: 'LOADING_RELATIVE_PRODUCT',
    LOAD_RELATIVE_PRODUCT_SUCCESS: 'LOAD_RELATIVE_PRODUCT_SUCCESS',
    LOAD_RELATIVE_PRODUCT_FAILURE: 'LOAD_RELATIVE_PRODUCT_FAILURE',

    CREATE_TEMP_ORDER: 'CREATE_TEMP_ORDER',
    CREATE_TEMP_ORDER_SUCCESS: 'CREATE_TEMP_ORDER_SUCCESS',
    CREATE_TEMP_ORDER_FAILURE: 'CREATE_TEMP_ORDER_FAILURE',

    LOAD_CURRENT_ITEM_STOCK: "LOAD_CURRENT_ITEM_STOCK",
    LOAD_CURRENT_ITEM_STOCK_SUCCESS: "LOAD_CURRENT_ITEM_STOCK_SUCCESS",

    CLEAR_CART_CHECKED: "CLEAR_CART_CHECKED",
    UPDATE_CART_CHECKED: "UPDATE_CART_CHECKED",

    LOAD_CART_SYNC_PRODUCT: 'LOAD_CART_SYNC_PRODUCT',
    LOADING_CART_SYNC_PRODUCT: 'LOADING_CART_SYNC_PRODUCT',
    LOAD_CART_SYNC_PRODUCT_SUCCESS: 'LOAD_CART_SYNC_PRODUCT_SUCCESS',
    LOAD_CART_SYNC_PRODUCT_FAILURE: 'LOAD_CART_SYNC_PRODUCT_FAILURE',

    LOAD_ADD_CART_SYNC_PRODUCT: 'LOAD_ADD_CART_SYNC_PRODUCT',
    LOADING_ADD_CART_SYNC_PRODUCT: 'LOADING_ADD_CART_SYNC_PRODUCT',
    LOAD_ADD_CART_SYNC_PRODUCT_SUCCESS: 'LOAD_ADD_CART_SYNC_PRODUCT_SUCCESS',
    LOAD_ADD_CART_SYNC_PRODUCT_FAILURE: 'LOAD_ADD_CART_SYNC_PRODUCT_FAILURE',
};

export default actions;
