const actions = {
    LOAD_INFORMATION_SYSTEM: 'LOAD_INFORMATION_SYSTEM',
    LOADING_INFORMATION_SYSTEM: 'LOADING_INFORMATION_SYSTEM',
    LOAD_INFORMATION_SYSTEM_SUCCESS: 'LOAD_INFORMATION_SYSTEM_SUCCESS',
    LOAD_INFORMATION_SYSTEM_FAILURE: 'LOAD_INFORMATION_SYSTEM_FAILURE',

    LOAD_ABOUT_US: 'LOAD_ABOUT_US',
    LOADING_ABOUT_US: 'LOADING_ABOUT_US',
    LOAD_ABOUT_US_SUCCESS: 'LOAD_ABOUT_US_SUCCESS',
    LOAD_ABOUT_US_FAILURE: 'LOAD_ABOUT_US_FAILURE',

};

export default actions;
