const LocationActions = {
    GET_CITY: 'GET_CITY',
    GET_CITY_SUCCESS: 'GET_CITY_SUCCESS',

    GET_DISTRICT: 'GET_DISTRICT',
    GET_DISTRICT_SUCCESS: 'GET_DISTRICT_SUCCESS',

    GET_WARD: 'GET_WARD',
    GET_WARD_SUCCESS: 'GET_WARD_SUCCESS',

    GET_CITY_RECRUITMENT: 'GET_CITY_RECRUITMENT',
    GET_CITY_RECRUITMENT_SUCCESS: 'GET_CITY_RECRUITMENT_SUCCESS',
};
export default LocationActions;
