// eslint-disable-next-line no-undef
const FaqActions = {
    LOAD_FAQ_TOPIC: 'LOAD_FAQ_TOPIC',
    LOAD_FAQ_TOPIC_SUCCESS: 'LOAD_FAQ_TOPIC_SUCCESS',

    LOAD_FAQ_QUESTIONS: 'LOAD_FAQ_QUESTIONS',
    LOAD_FAQ_QUESTIONS_SUCCESS: 'LOAD_FAQ_QUESTIONS_SUCCESS',

    LOAD_FAQ_ANSWER: 'LOAD_FAQ_ANSWER',
    LOAD_FAQ_ANSWER_SUCCESS: 'LOAD_FAQ_ANSWER_SUCCESS',

    SEARCH_FAQ: 'SEARCH_FAQ',
    SEARCH_FAQ_SUCCESS: 'SEARCH_FAQ_SUCCESS',

    SEARCH_FAQ_BY_TYPE: 'SEARCH_FAQ_BY_TYPE',
    SEARCH_FAQ_BY_TYPE_SUCCESS: 'SEARCH_FAQ_BY_TYPE_SUCCESS',
};

export default FaqActions;
