const actions = {
    LOAD_USER_ORDER_ADDRESS: 'LOAD_USER_ORDER_ADDRESS',
    LOAD_USER_ORDER_ADDRESS_SUCCESS: 'LOAD_USER_ORDER_ADDRESS_SUCCESS',
    LOAD_USER_ORDER_ADDRESS_FAILURE: 'LOAD_USER_ORDER_ADDRESS_FAILURE',

    UPDATE_ORDER_VALUES: 'UPDATE_ORDER_VALUES',
    CALC_ORDER_VALUES: 'CALC_ORDER_VALUES',
    CALC_ORDER_VALUES_SUCCESS: 'CALC_ORDER_VALUES_SUCCESS',
    CALC_ORDER_VALUES_FAILURE: 'CALC_ORDER_VALUES_FAILURE',

    CALC_ORDER_VALUES_SYNC: 'CALC_ORDER_VALUES_SYNC',
    CALC_ORDER_VALUES_SYNC_SUCCESS: 'CALC_ORDER_VALUES_SYNC_SUCCESS',
    CALC_ORDER_VALUES_SYNC_FAILURE: 'CALC_ORDER_VALUES_SYNC_FAILURE',

    GET_ORDER_VOUCHER: 'GET_ORDER_VOUCHER',
    GET_ORDER_VOUCHER_SUCCESS: 'GET_ORDER_VOUCHER_SUCCESS',
    GET_ORDER_VOUCHER_FAILURE: 'GET_ORDER_VOUCHER_FAILURE',

    SET_ORDER_ERROR_MESSAGE: 'SET_ORDER_ERROR_MESSAGE',

    SAVE_ORDER: 'SAVE_ORDER',
    SAVE_ORDER_SUCCESS: 'SAVE_ORDER_SUCCESS',
    SAVE_ORDER_FAILURE: 'SAVE_ORDER_FAILURE',

    SAVE_ORDER_SYNC: 'SAVE_ORDER_SYNC',
    SAVE_ORDER_SYNC_SUCCESS: 'SAVE_ORDER_SYNC_SUCCESS',
    SAVE_ORDER_SYNC_FAILURE: 'SAVE_ORDER_SYNC_FAILURE',

    SAVE_USER_ADDRESS: 'SAVE_USER_ADDRESS',
    SAVE_USER_ADDRESS_SUCCESS: 'SAVE_USER_ADDRESS_SUCCESS',
    SAVE_USER_ADDRESS_FAILURE: 'SAVE_USER_ADDRESS_FAILURE',

    DELETE_USER_ADDRESS: 'DELETE_USER_ADDRESS',
    DELETE_USER_ADDRESS_SUCCESS: 'DELETE_USER_ADDRESS_SUCCESS',
    DELETE_USER_ADDRESS_FAILURE: 'DELETE_USER_ADDRESS_FAILURE',

    GET_ID_CREATE_ADDRESS_SUCCESS:'GET_ID_CREATE_ADDRESS_SUCCESS',
};

export default actions;