// eslint-disable-next-line no-undef
const RecruitmentActions = {
    LOAD_RECRUITMENT_LIST: 'LOAD_RECRUITMENT_LIST',
    LOAD_RECRUITMENT_LIST_RESPONSE: 'LOAD_RECRUITMENT_LIST_RESPONSE',

    LOAD_RECRUITMENT_DETAIL: 'LOAD_RECRUITMENT_DETAIL',
    LOAD_RECRUITMENT_DETAIL_RESPONSE: 'LOAD_RECRUITMENT_DETAIL_RESPONSE',

    LOAD_POSITION_TYPE: 'LOAD_POSITION_TYPE',
    LOAD_POSITION_TYPE_RESPONSE: 'LOAD_POSITION_TYPE_RESPONSE',

    RECRUITMENT_APPLY: 'RECRUITMENT_APPLY',

    LOAD_RECRUITMENT_LIST_LOADING: 'LOAD_RECRUITMENT_LIST_LOADING',
    LOAD_RECRUITMENT_LIST_MOBILE: 'LOAD_RECRUITMENT_LIST_MOBILE',
    LOAD_RECRUITMENT_LIST_MOBILE_RESPONSE: 'LOAD_RECRUITMENT_LIST_MOBILE_RESPONSE',
    LOAD_RECRUITMENT_LIST_MOBILE_FAIL: 'LOAD_RECRUITMENT_LIST_MOBILE_FAIL',
};
export default RecruitmentActions;
