export const AuthActions = {

    GET_USER: 'GET_USER',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_PROFILE: 'GET_USER_PROFILE',
    GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',

    UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
    UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',

    RESEND_OTP: 'RESEND_OTP',

    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    CHECK_OTP_FORGOT_PASSWORD: 'CHECK_OTP_FORGOT_PASSWORD',
    RESEND_OTP_FORGOT_PASSWORD: 'RESEND_OTP_FORGOT_PASSWORD',
    LOGOUT: 'LOGOUT',

    SEND_OTP_PHONE: 'SEND_OTP_PHONE',
    SEND_OTP_EMAIL: 'SEND_OTP_EMAIL',
    UPDATE_PHONE:'UPDATE_PHONE',
    UPDATE_EMAIL:'UPDATE_EMAIL',
};

export default AuthActions;
