const actions = {
    LOAD_ORDER_DETAIL: 'LOAD_ORDER_DETAIL',
    LOADING_ORDER_DETAIL: 'LOADING_ORDER_DETAIL',
    LOAD_ORDER_DETAIL_SUCCESS: 'LOAD_ORDER_DETAIL_SUCCESS',
    LOAD_ORDER_DETAIL_FAILURE: 'LOAD_ORDER_DETAIL_FAILURE',

    CANCEL_ORDER: 'CANCEL_ORDER',
    CANCELLING_ORDER: 'CANCELLING_ORDER',
    CANCEL_ORDER_SUCCESS: 'CANCEL_ORDER_SUCCESS',
    CANCEL_ORDER_FAILURE: 'CANCEL_ORDER_FAILURE',

    REVIEW_ORDER: 'REVIEW_ORDER',
    REVIEWING_ORDER: 'REVIEWING_ORDER',
    REVIEW_ORDER_SUCCESS: 'REVIEW_ORDER_SUCCESS',
    REVIEW_ORDER_FAILURE: 'REVIEW_ORDER_FAILURE',
};

export default actions;
