const actions = {
    LOAD_WISHLIST: 'LOAD_WISHLIST',
    LOADING_WISHLIST: 'LOADING_WISHLIST',
    LOAD_WISHLIST_SUCCESS: 'LOAD_WISHLIST_SUCCESS',
    LOAD_WISHLIST_FAILURE: 'LOAD_WISHLIST_FAILURE',

    ADD_WISHLIST: 'ADD_WISHLIST',
    ADDING_WISHLIST: 'ADDING_WISHLIST',
    ADD_WISHLIST_SUCCESS: 'ADD_WISHLIST_SUCCESS',
    ADD_WISHLIST_FAILURE: 'ADD_WISHLIST_FAILURE',

    REMOVE_ITEM_WISHLIST: 'REMOVE_ITEM_WISHLIST',
    REMOVING_ITEM_WISHLIST: 'REMOVING_ITEM_WISHLIST',
    REMOVE_ITEM_WISHLIST_SUCCESS: 'REMOVE_ITEM_WISHLIST_SUCCESS',
    REMOVE_ITEM_WISHLIST_FAILURE: 'REMOVE_ITEM_WISHLIST_FAILURE',

    EXPORT_WISHLIST_FOR_SALE: 'EXPORT_WISHLIST_FOR_SALE',
    LOADING_EXPORT_WISHLIST_FOR_SALE: 'LOADING_EXPORT_WISHLIST_FOR_SALE',
    EXPORT_WISHLIST_FOR_SALE_SUCCESS: 'EXPORT_WISHLIST_FOR_SALE_SUCCESS',
    EXPORT_WISHLIST_FOR_SALE_FAILURE: 'EXPORT_WISHLIST_FOR_SALE_FAILURE',
};

export default actions;
