const actions = {
    SUBMIT_LOGIN: 'SUBMIT_LOGIN',
    SUBMITING_LOGIN: 'SUBMITING_LOGIN',
    SUBMIT_LOGIN_SUCCESS: 'SUBMIT_LOGIN_SUCCESS',
    SUBMIT_LOGIN_FAILURE: 'SUBMIT_LOGIN_FAILURE',

    RESET_FORM_LOGIN: 'RESET_FORM_LOGIN',
    RESET_SIGN_IN: 'RESET_SIGN_IN',

    REFRESH_TOKEN: 'REFRESH_TOKEN',
    LOADING_REFRESH_TOKEN: 'LOADING_REFRESH_TOKEN',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
    REFRESH_TOKEN_FAILURE: 'REFRESH_TOKEN_FAILURE',

    AUTH_SOCIAL: 'AUTH_SOCIAL',
    AUTH_SOCIAL_SUCCESS: 'AUTH_SOCIAL_SUCCESS',
};

export default actions;
