const actions = {
    LOAD_PRODUCT_LIST_WITH_TYPE_START: 'LOAD_PRODUCT_LIST_WITH_TYPE_START',
    LOAD_PRODUCT_LIST_WITH_TYPE_LOADING: 'LOAD_PRODUCT_LIST_WITH_TYPE_LOADING',
    LOAD_PRODUCT_LIST_WITH_TYPE_SUCCESS: 'LOAD_PRODUCT_LIST_WITH_TYPE_SUCCESS',
    LOAD_PRODUCT_LIST_WITH_TYPE_FAIL: 'LOAD_PRODUCT_LIST_WITH_TYPE_FAIL',

    LOAD_PRODUCT_LIST_WITH_SALE_TYPE_START: 'LOAD_PRODUCT_LIST_WITH_SALE_TYPE_START',
    LOAD_PRODUCT_LIST_WITH_SALE_TYPE_LOADING: 'LOAD_PRODUCT_LIST_WITH_SALE_TYPE_LOADING',
    LOAD_PRODUCT_LIST_WITH_SALE_TYPE_SUCCESS: 'LOAD_PRODUCT_LIST_WITH_SALE_TYPE_SUCCESS',
    LOAD_PRODUCT_LIST_WITH_SALE_TYPE_FAIL: 'LOAD_PRODUCT_LIST_WITH_SALE_TYPE_FAIL',
}


export default actions;