const actions = {
    LOAD_WATCHED_PRODUCT_LIST: 'LOAD_WATCHED_PRODUCT_LIST',
    LOADING_WATCHED_PRODUCT_LIST: 'LOADING_WATCHED_PRODUCT_LIST',
    LOAD_WATCHED_PRODUCT_LIST_SUCCESS: 'LOAD_WATCHED_PRODUCT_LIST_SUCCESS',
};

export default actions;
