const Actions = {
    GET_ORDER_BY_STATUS: 'GET_ORDER_BY_STATUS',
    GET_ORDER_BY_STATUS_RESPONSE: 'GET_ORDER_BY_STATUS_RESPONSE',

    GET_REVIEW_DETAIL: 'GET_REVIEW_DETAIL',
    GET_REVIEW_DETAIL_RESPONSE: 'GET_REVIEW_DETAIL_RESPONSE',

    GET_ORDER_DETAIL: 'GET_ORDER_DETAIL',
    GET_ORDER_DETAIL_RESPONSE: 'GET_ORDER_DETAIL_RESPONSE',

    CANCEL_ORDER: 'CANCEL_ORDER',
    CANCEL_ORDER_RESPONSE: 'CANCEL_ORDER_RESPONSE',

    REVIEW_ORDER: 'REVIEW_ORDER',
    RECEIVED_ORDER: 'RECEIVED_ORDER',
    ORDER_REFUND_REQUEST: 'ORDER_REFUND_REQUEST',

    GET_CANCEL_REASON: 'GET_CANCEL_REASON',
    GET_CANCEL_REASON_RESPONSE: 'GET_CANCEL_REASON_RESPONSE',

    ON_REORDER: 'ON_REORDER',
    RETURN_ORDER: 'RETURN_ORDER',
};
export default Actions;
