// eslint-disable-next-line no-undef
const WalletActions = {
    LOAD_POINT_HISTORY: "LOAD_POINT_HISTORY",
    LOAD_POINT_HISTORY_SUCCESS: "LOAD_POINT_HISTORY_SUCCESS",
    LOAD_POINT_HISTORY_FAILURE: "LOAD_POINT_HISTORY_FAILURE",

    LOAD_VOUCHER: "LOAD_VOUCHER",
    LOAD_VOUCHER_SUCCESS: "LOAD_VOUCHER_SUCCESS",
    LOAD_VOUCHER_FAILURE: "LOAD_VOUCHER_FAILURE",

    LOAD_POINT_HISTORY_DETAIL: "LOAD_POINT_HISTORY_DETAIL",
    LOAD_POINT_HISTORY_DETAIL_SUCCESS: "LOAD_POINT_HISTORY_DETAIL_SUCCESS",
    LOAD_POINT_HISTORY_DETAIL_FAILURE: "LOAD_POINT_HISTORY_DETAIL_FAILURE",
};

export default WalletActions;
