const actions = {
    FILTER_ITEM: 'FILTER_ITEM',
    FILTERRING_ITEM: 'FILTERRING_ITEM',
    FILTER_ITEM_SUCCESS: 'FILTER_ITEM_SUCCESS',
    FILTER_ITEM_FAILURE: 'FILTER_ITEM_FAILURE',

    FILTER_ITEM_LOAD_MORE: 'FILTER_ITEM_LOAD_MORE',
    FILTERRING_ITEM_LOAD_MORE: 'FILTERRING_ITEM_LOAD_MORE',
    FILTER_ITEM_LOAD_MORE_SUCCESS: 'FILTER_ITEM_LOAD_MORE_SUCCESS',
    FILTER_ITEM_LOAD_MORE_FAILURE: 'FILTER_ITEM_LOAD_MORE_FAILURE',

    UPDATE_GENDER_SELECTED: "UPDATE_GENDER_SELECTED",
    UPDATE_CATEGORY_SELECTED: "UPDATE_CATEGORY_SELECTED",
    UPDATE_CATEGORY_SECOND_SELECTED: "UPDATE_CATEGORY_SECOND_SELECTED",
    UPDATE_BRAND_SELECTED: "UPDATE_BRAND_SELECTED",
    UPDATE_HOTTREND_SELECTED: "UPDATE_HOTTREND_SELECTED",

    TOGGLE_SEARCH_ADVANCED_SCREEN: "TOGGLE_SEARCH_ADVANCED_SCREEN",
    TOGGLE_GENDER_SCREEN: "TOGGLE_GENDER_SCREEN",
    TOGGLE_CATEGORY_SCREEN: "TOGGLE_CATEGORY_SCREEN",
    TOGGLE_CATEGORY_SECOND_SCREEN: "TOGGLE_CATEGORY_SECOND_SCREEN",
    TOGGLE_BRAND_SCREEN: "TOGGLE_BRAND_SCREEN",
    TOGGLE_HOTTREND_SCREEN: "TOGGLE_HOTTREND_SCREEN",

    SEARCH_ITEM: 'SEARCH_ITEM',
    SEARCH_ITEM_SUCCESS: 'SEARCH_ITEM_SUCCESS',
    SEARCH_ITEM_FAILURE: 'SEARCH_ITEM_FAILURE',
    SEARCHING_ITEM: 'SEARCHING_ITEM',

    GET_CURRENT_CATEGORY: 'GET_CURRENT_CATEGORY',
    GETTING_CURRENT_CATEGORY: 'GETTING_CURRENT_CATEGORY',
    GET_CURRENT_CATEGORY_SUCCESS: 'GET_CURRENT_CATEGORY_SUCCESS',
    GET_CURRENT_CATEGORY_FAILURE: 'GET_CURRENT_CATEGORY_FAILURE',

    GET_BRAND_NAME: "GET_BRAND_NAME",
    GETTING_BRAND_NAME: "GETTING_BRAND_NAME",
    GET_BRAND_NAME_SUCCESS: "GET_BRAND_NAME_SUCCESS",
    GET_BRAND_NAME_FAILURE: "GET_BRAND_NAME_FAILURE",

    GET_CATEGORY_NAME: "GET_CATEGORY_NAME",
    GETTING_CATEGORY_NAME: "GETTING_CATEGORY_NAME",
    GET_CATEGORY_NAME_SUCCESS: "GET_CATEGORY_NAME_SUCCESS",
    GET_CATEGORY_NAME_FAILURE: "GET_CATEGORY_NAME_FAILURE",
};

export default actions;
