const actions = {
    SUBMIT_SIGN_UP: 'SUBMIT_SIGN_UP',
    SUBMITING_SIGN_UP: 'SUBMITING_SIGN_UP',
    SUBMIT_SIGN_UP_SUCCESS: 'SUBMIT_SIGN_UP_SUCCESS',
    SUBMIT_SIGN_UP_FAILURE: 'SUBMIT_SIGN_UP_FAILURE',

    SIGN_UP_STEP_ONE: 'SIGN_UP_STEP_ONE',
    SIGN_UP_STEP_TWO: 'SIGN_UP_STEP_TWO',
    SIGN_UP_VERIFY_OTP: 'SIGN_UP_VERIFY_OTP',
    RESET_SIGN_UP: "RESET_SIGN_UP"
};

export default actions;
